package container

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/useurmind/djinni/pkg/log"
)

const DefaultSquidPort = 3128

// GenerateSquidConfig generates a squid.conf file based on network configuration
func GenerateSquidConfig(enabled bool, allowList []string, port int, baseDir, repoName, agentName, taskName string) (string, error) {
	if !enabled {
		return "", nil
	}

	// Create temp directory for squid config
	tempDir := filepath.Join(baseDir, "proxyConfig", repoName, agentName, taskName)
	if err := os.MkdirAll(tempDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create temp directory for squid config: %w", err)
	}

	configPath := filepath.Join(tempDir, "squid.conf")

	var builder strings.Builder

	// Basic Squid configuration
	builder.WriteString("# Squid configuration generated by Djinni\n")
	builder.WriteString("\n")

	// ACL definitions based on allow list
	builder.WriteString("# ACL definitions\n")
	for i, allowedURL := range allowList {
		// Extract domain from URL if possible
		domain := extractDomain(allowedURL)
		if domain != "" {
			fmt.Fprintf(&builder, "acl allowed_%d dstdomain %s\n", i, domain)
		}
	}
	builder.WriteString("\n")

	// HTTP access rules
	builder.WriteString("# HTTP access rules\n")
	builder.WriteString("http_access deny all\n") // Default deny
	for i := range allowList {
		fmt.Fprintf(&builder, "http_access allow allowed_%d\n", i)
	}
	builder.WriteString("\n")

	// Cache settings
	builder.WriteString("# Cache settings\n")
	builder.WriteString("cache_mem 32 MB\n")
	builder.WriteString("maximum_object_size 10 MB\n")
	builder.WriteString("\n")

	// Port configuration
	builder.WriteString("# Port configuration\n")
	fmt.Fprintf(&builder, "http_port %d\n", port)
	builder.WriteString("\n")

	// Logging
	builder.WriteString("# Logging\n")
	builder.WriteString("access_log /var/log/squid/access.log\n")
	builder.WriteString("cache_log /var/log/squid/cache.log\n")

	// Write to file
	if err := os.WriteFile(configPath, []byte(builder.String()), 0644); err != nil {
		return "", fmt.Errorf("failed to write squid config: %w", err)
	}

	log.Info(fmt.Sprintf("Generated Squid configuration at: %s", configPath))
	return configPath, nil
}

// extractDomain extracts the domain from a URL
func extractDomain(url string) string {
	// Remove protocol
	url = strings.TrimPrefix(url, "http://")
	url = strings.TrimPrefix(url, "https://")

	// Remove path
	if idx := strings.Index(url, "/"); idx != -1 {
		url = url[:idx]
	}

	// Remove port if present
	if idx := strings.Index(url, ":"); idx != -1 {
		url = url[:idx]
	}

	return url
}

// CleanupProxyConfig cleans up generated proxy configuration files
func CleanupProxyConfig(baseDir, repoName, agentName, taskName string) error {
	tempDir := filepath.Join(baseDir, "proxyConfig", repoName, agentName, taskName)
	if err := os.RemoveAll(tempDir); err != nil {
		return fmt.Errorf("failed to cleanup proxy config: %w", err)
	}
	return nil
}

// StartProxyContainer creates and starts the Squid proxy container
func StartProxyContainer(client *Client, configPath string, networkName, proxyContainerName string, squidPort int) (string, error) {
	args := []string{
		"run", "--rm", "-d",
		"--name", proxyContainerName,
		"--network", networkName,
		"-v", fmt.Sprintf("%s:/etc/squid/squid.conf:Z,ro,U", configPath),
		"-p", fmt.Sprintf("%d:%d", squidPort, squidPort),
		"ubuntu/squid:latest",
	}

	cmd := exec.Command(client.Binary, args...)
	_, err := cmd.CombinedOutput()
	if err != nil {
		return "", fmt.Errorf("failed to start proxy container: %w", err)
	}

	log.Info(fmt.Sprintf("Started proxy container: %s", proxyContainerName))
	return proxyContainerName, nil
}

// ConnectProxyToInternet connects the proxy container to the bridge network for internet access
func ConnectProxyToInternet(client *Client, proxyContainerName string) error {
	// Connect proxy to bridge network (podman default for internet)
	args := []string{"network", "connect", "bridge", proxyContainerName}

	cmd := exec.Command(client.Binary, args...)
	_, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("failed to connect proxy container %s to bridge network: %w", proxyContainerName, err)
	}

	log.Info(fmt.Sprintf("Connected proxy container %s to bridge network", proxyContainerName))
	return nil
}

// StopProxyContainer stops the Squid proxy container
func StopProxyContainer(client *Client, proxyContainerName string) error {
	args := []string{"stop", proxyContainerName}

	cmd := exec.Command(client.Binary, args...)
	_, err := cmd.CombinedOutput()
	if err != nil {
		// Check if the error is because the container doesn't exist
		// podman returns exit status 125 for "container not found"
		if exitErr, ok := err.(*exec.ExitError); ok && exitErr.ExitCode() == 125 {
			log.Info(fmt.Sprintf("Container %s does not exist, nothing to stop", proxyContainerName))
			return nil
		}
		return fmt.Errorf("failed to stop proxy container %s: %w", proxyContainerName, err)
	}

	log.Info(fmt.Sprintf("Stopped proxy container: %s", proxyContainerName))
	return nil
}

// RemoveProxyContainer removes the Squid proxy container
func RemoveProxyContainer(client *Client, proxyContainerName string) error {
	args := []string{"rm", proxyContainerName}

	cmd := exec.Command(client.Binary, args...)
	_, err := cmd.CombinedOutput()
	if err != nil {
		// Check if the error is because the container doesn't exist
		// podman returns exit status 125 for "container not found"
		if exitErr, ok := err.(*exec.ExitError); ok && exitErr.ExitCode() == 125 {
			log.Info(fmt.Sprintf("Container %s does not exist, nothing to remove", proxyContainerName))
			return nil
		}
		return fmt.Errorf("failed to remove proxy container %s: %w", proxyContainerName, err)
	}

	log.Info(fmt.Sprintf("Removed proxy container: %s", proxyContainerName))
	return nil
}
